### PR TITLE
Add support for job.workdir

### PR DESCRIPTION
**Pull request by dlecocq**
Other language bindings include a `job.workdir` while processing a job that provides a workspace that is guaranteed to be clean before the job runs, and cleaned up after the job runs. The worker also guarantees that the workspace is cleaned up when starting up, which helps in the event that the worker completely crashes.

This seeks to add that functionality here.

### CODE REVIEW

**Comment by dlecocq** [comment]
@evanbattaglia @b4hand @lindseyreno - do y'all know who might still be around to merge this?

**Comment by lindseyreno** [comment]
@a1ph4g33k maybe?

**Comment by a1ph4g33k** [comment]
Sorry I've been out on Medical leave for the last 2 months (ongoing). Merged.

**Comment by dlecocq** [comment]
🙇  Thank you!

**Pull request merged**
